#include "pch.h"

#ifndef CyberInterposer_NGX_Types
#define CyberInterposer_NGX_Types

namespace CyberTypes {
	typedef AppId CT_AppId;
	typedef NVSDK_NGX_DLSS_Hint_Render_Preset CT_NVSDK_NGX_DLSS_Hint_Render_Preset;
	typedef NVSDK_NGX_FeatureCommonInfo_Internal CT_NVSDK_NGX_FeatureCommonInfo_Internal;
	typedef NVSDK_NGX_Version CT_NVSDK_NGX_Version;
	typedef NVSDK_NGX_Result CT_NVSDK_NGX_Result;
	typedef NVSDK_NGX_Feature CT_NVSDK_NGX_Feature;
	typedef NVSDK_NGX_Buffer_Format CT_NVSDK_NGX_Buffer_Format;
	typedef NVSDK_NGX_PerfQuality_Value CT_NVSDK_NGX_PerfQuality_Value;
	typedef NVSDK_NGX_RTX_Value CT_NVSDK_NGX_RTX_Value;
	typedef NVSDK_NGX_DLSS_Mode CT_NVSDK_NGX_DLSS_Mode;
	typedef NVSDK_NGX_DeepDVC_Mode CT_NVSDK_NGX_DeepDVC_Mode;
	typedef NVSDK_NGX_Handle CT_NVSDK_NGX_Handle;
	typedef NSDK_NGX_GPU_Arch CT_NSDK_NGX_GPU_Arch;
	typedef NVSDK_NGX_DLSS_Feature_Flags CT_NVSDK_NGX_DLSS_Feature_Flags;
	typedef NVSDK_NGX_ToneMapperType CT_NVSDK_NGX_ToneMapperType;
	typedef NVSDK_NGX_GBufferType CT_NVSDK_NGX_GBufferType;
	typedef NVSDK_NGX_Coordinates CT_NVSDK_NGX_Coordinates;
	typedef NVSDK_NGX_Dimensions CT_NVSDK_NGX_Dimensions;
	typedef NVSDK_NGX_PathListInfo CT_NVSDK_NGX_PathListInfo;
	typedef NVSDK_NGX_Logging_Level CT_NVSDK_NGX_Logging_Level;
	typedef NVSDK_NGX_FeatureCommonInfo CT_NVSDK_NGX_FeatureCommonInfo;
	typedef NVSDK_NGX_Resource_VK_Type CT_NVSDK_NGX_Resource_VK_Type;
	typedef NVSDK_NGX_Opt_Level CT_NVSDK_NGX_Opt_Level;
	typedef NVSDK_NGX_EngineType CT_NVSDK_NGX_EngineType;
	typedef NVSDK_NGX_Feature_Support_Result CT_NVSDK_NGX_Feature_Support_Result;
	typedef NVSDK_NGX_Application_Identifier_Type CT_NVSDK_NGX_Application_Identifier_Type;
	typedef NVSDK_NGX_ProjectIdDescription CT_NVSDK_NGX_ProjectIdDescription;
	typedef NVSDK_NGX_Application_Identifier CT_NVSDK_NGX_Application_Identifier;
	typedef NVSDK_NGX_FeatureDiscoveryInfo CT_NVSDK_NGX_FeatureDiscoveryInfo;
	typedef NVSDK_NGX_FeatureRequirement CT_NVSDK_NGX_FeatureRequirement;
}

#endif